# Generated by Django 5.0 on 2025-12-03 05:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='like',
            name='loop',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='loop',
            options={},
        ),
        migrations.RemoveField(
            model_name='loop',
            name='category',
        ),
        migrations.RemoveField(
            model_name='loop',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='loop',
            name='is_premium',
        ),
        migrations.RemoveField(
            model_name='loop',
            name='price',
        ),
        migrations.RemoveField(
            model_name='loop',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='loop',
            name='video_url',
        ),
        migrations.AlterField(
            model_name='loop',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='loop',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
