# Generated by Django 5.0 on 2025-12-04 04:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loops', '0002_alter_like_unique_together_remove_like_loop_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loop',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='loop',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='loop_attachments/'),
        ),
        migrations.AddField(
            model_name='loop',
            name='category',
            field=models.CharField(choices=[('General', 'General'), ('Math', 'Mathematics'), ('Science', 'Science'), ('CS', 'Computer Science'), ('Business', 'Business'), ('Arts', 'Arts & Humanities'), ('Language', 'Languages'), ('Engineering', 'Engineering'), ('Medicine', 'Medicine'), ('Law', 'Law'), ('Other', 'Other')], default='General', max_length=50),
        ),
        migrations.AddField(
            model_name='loop',
            name='difficulty',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Beginner', max_length=20),
        ),
        migrations.AddField(
            model_name='loop',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loop',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='loop',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='loop',
            name='video_url',
            field=models.URLField(blank=True, help_text='Optional YouTube/Vimeo link', null=True),
        ),
        migrations.AddField(
            model_name='loop',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='loop',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_loops', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='loops.loop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='loops.loop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'loop')},
            },
        ),
    ]
