# Generated by Django 6.0 on 2025-12-07 04:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loops', '0003_alter_loop_options_loop_attachment_loop_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='loop',
            name='is_purchased_by',
            field=models.ManyToManyField(blank=True, related_name='purchased_loops', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='loop',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
